### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by jeffbourdier** [jeffbourdier/midi2sql#1]
Update README.md with usage, command line options, similar apps, build notes, etc.

**Comment by dave234** [comment]
A quick pointer of where to start reading, and a high level overview would be really helpful :)

**Comment by jeffbourdier** [comment]
Usage, command line options, similar apps, and build notes added.  Data model, use cases, and examples coming.  Let me know what else would be helpful.

**Comment by jeffbourdier** [comment]
Resolved with commit d9176a1d56a5138ff3900ec124b8ad07354eadb4.

**Comment by dave234** [comment]
🤘
